/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    SubTask: typeof import('./src/components/SubTask.vue')['default']
    TaskDetail: typeof import('./src/components/TaskDetail.vue')['default']
    TaskGroup: typeof import('./src/components/TaskGroup.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
  }
}
